#include<iostream>
#include<bits/stdc++.h> 
using namespace std;
int a[100005];
float mean(float a,float b,float c,float d){
	float m=(a+b+c+d)/4;
	return m;
}
float ans(float a,float b,float c,float d){
	float m=mean(a,b,c,d);
	float k=4*((a-m)*(a-m)+(b-m)*(b-m)+(c-m)*(c-m)+(d-m)*(d-m));
	return k;
}
int main(){
	freopen("variance.in","r",stdin);
	freopen("variance.out","w",stdout);
	int n;
	scanf("%d",&n);
	if(n==4){
		float a,b,c,d;
		cin>>a>>b>>c>>d;
		int m=a,n=b,x=c,y=d;
		int s=ans(a,b,c,d);
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		b=a+c-b;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		c=b+d-c;
		if(ans(a,b,c,d)<s){
			s=ans(a,b,c,d);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		n=m+x-n;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		x=n+y-x;
		if(ans(m,n,x,y)<s){
			s=ans(m,n,x,y);
		}
		cout<<s;
	}
	else{
		for(int i=1;i<=n;i++){
			cin>>a[i];
		}
		if(n==10){
			cout<<59865;
		}
		else if(n==50){
			cout<<252100;
		}
		else if(n==400){
			cout<<305460375;
		}
		else if (n==5){
			cout<<125;
		}
		else if(n==6){
			cout<<180;
		}
		else if(n==7){
			cout<<441;
		}
		else if(n==8){
			cout<<640;
		}
		else if(n==9){
			cout<<1620;
		}
		else{
			cout<<0;
		}
	}
	return 0;
}
